app/models.py
from app import db
from flask import current_app
from hashlib import md5
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from app import login

@login.user_loader
def load_user(id):
    return User.query.get(int(id))

class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    firstname = db.Column(db.String(40), index=True)
    lastname = db.Column(db.String(40), index=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))

    def __repr__(self):
        return '<User {}, {}>'.format(self.username, self.role)

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

class Favorites(db.Model):
    id = db.Column(db.Integer, primary_key = True)
    user_id = db.Column(db.Integer, db.ForeignKey(User.id))
    user = db.relationship('User', foreign_keys = 'Favorites.user_id', lazy = 'joined')
    word = db.Column(db.String(100), index=True)

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms.validators import DataRequired, ValidationError
from wtforms import StringField, SubmitField
import re

class SearchForm(FlaskForm):
    word = StringField('Meaning for :', validators=[DataRequired()])
    submit = SubmitField('Search')

    def validate_word(self, word):
        pat = re.compile("^[a-zA-Z-]+$")
        if pat.match(word.data) is None:
            raise ValidationError('Word can contain alphabets only')
    

app/__init__.py
from flask import Flask
from config import Config
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from flask_bootstrap import Bootstrap
from flask_login import LoginManager
from config import Config

db = SQLAlchemy()
migrate = Migrate()
login = LoginManager()
login.login_view = 'auth.login'
bootstrap = Bootstrap()

def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(config_class)

    db.init_app(app)
    migrate.init_app(app, db)
    login.init_app(app)
    bootstrap.init_app(app)

    from app.auth import bp as auth_bp
    app.register_blueprint(auth_bp, url_prefix='/auth')

    from app.main import bp as main_bp
    app.register_blueprint(main_bp)

    return app

from app import models

app/main/__init__.py
from flask import Blueprint

bp = Blueprint('main', __name__)

from app.main import routes

app/main/routes.py
from flask import render_template, flash, redirect, url_for, request, make_response
from flask_login import current_user, login_required
from app import db
from app.main import bp
from app.models import User, Favorites
from app.main.forms import SearchForm
import urllib.request, json 
from config import KEY

API_Request = 'https://www.dictionaryapi.com/api/v3/references/thesaurus/json/{}?key='+KEY

@bp.route('/')
@bp.route('/index')
def index():
    return render_template('index.html')

@bp.route('/profile')
@login_required
def profile():
    id = current_user.id
    user = User.query.filter_by(id=id).first()
    favorites = Favorites.query.filter_by(user_id=id).all()
    num = str(len(favorites))
    name = user.firstname + " " + user.lastname
    return render_template('profile.html', title = 'Profile', name = name, user = user, num = num)

@bp.route('/favorites')
@login_required
def favorites():
    favorites = Favorites.query.filter_by(user_id = current_user.id).all()
    cards = []
    for item in favorites:
        tmp = {}
        tmp['word'] = item.word.capitalize()
        tmp['meanings'] = []
        data = fetch_meaning(item.word)
        cnt = 0
        for meaning in data:
            single_meaning = {}
            single_meaning['part'] = meaning['fl']
            single_meaning['def'] = meaning['shortdef'][0]
            tmp['meanings'].append(single_meaning)
            cnt+=1
            if cnt >= 2:
                break
        cards.append(tmp)
    
    rows_of_cards = []
    for i in range(0, len(cards), 3):
        rows_of_cards.append(cards[i:i+3])
    print(rows_of_cards)

    return render_template('favorites.html', title = 'Favorites', favorites = favorites, rows = rows_of_cards)


def fetch_meaning(word):
    req = API_Request.format(word.replace(" ", "%20"))
    url = urllib.request.urlopen(req)
    data = json.loads(url.read().decode())
    return data


@bp.route('/search', methods = ['POST', 'GET'])
@login_required
def search():
    form = SearchForm()
    dne = False
    data = None
    is_favorite = False
    word = ""
    favorites = Favorites.query.filter_by(user_id = current_user.id).all()

    if form.validate_on_submit():
        word = form.word.data
        data = fetch_meaning(word)
        
        try:
            tmp = data[0]['shortdef'][0]
            for item in favorites:
                if item.word == word:
                    is_favorite = True
                    break
        except:
            dne = True
        
        resp = make_response(render_template('search.html', title = 'Search', form = form, is_favorite = is_favorite, dne = dne, data = data, word = word))
        if not dne:
            resp.set_cookie('word', word)
        return resp
    
    if 'word' in request.cookies:
        word = request.cookies.get('word')
    form.word.data = word
    data = fetch_meaning(word)
    for item in favorites:
        if item.word == word:
            is_favorite = True
            break

    return render_template('search.html', title = 'Search', form = form, is_favorite = is_favorite, dne = dne, data = data, word = word)


@bp.route('/AddToFavorites/<word>', methods = ['GET'])
@login_required
def add_to_favorites(word):
    tmp = Favorites.query.filter_by(user_id = current_user.id, word = word).all()
    if len(tmp) == 0:
        entry = Favorites(user_id = current_user.id, word = word)
        db.session.add(entry)
        db.session.commit()
        flash('Added ' + word + ' to favorites')
    else:
        flash(word + 'already in favorites')
    return redirect(url_for('main.search'))

@bp.route('/RemoveFromFavorites/<word>', methods = ['GET'])
@login_required
def remove_from_favorites(word):
    entry = Favorites.query.filter_by(user_id = current_user.id, word = word).first()
    db.session.delete(entry)
    db.session.commit()
    flash('Removed ' + word + ' from favorites')
    return redirect(url_for('main.search'))

app/templates/base.html
{% extends 'bootstrap/base.html' %}


{% block title %}
    {% if title %} {{ title }} - Diktionary {% else %} Welcome to Diktionary {% endif %}
{% endblock %}

{% block navbar %}
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">Diktionary</a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a href="{{ url_for('main.search') }}">Find Meaning 🔎</a></li>
                    <li><a href="{{ url_for('main.favorites')}}">Flash Cards ❤️</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li><a href="{{ url_for('main.profile') }}">Profile 👤</a></li>
                    {% if current_user.is_anonymous %}
                        <li><a href="{{ url_for('auth.login') }}"> Login | Sign Up</a></li>
                    {% elif current_user.is_authenticated %}
                        <li><a href="{{ url_for('auth.logout') }}" id = "logout">Logout</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}

{% block content %}
    <div class="container">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-info" role="alert">{{ message }}</div>
            {% endfor %}
        {% endif %}
        {% endwith %}

        {# application content needs to be provided in the app_content block #}
        {% block app_content %}{% endblock %}
    </div>
{% endblock %}

app/templates/favorites.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}

{% block styles %}
{{ super() }}
<style>
    .card {
  position: relative;
  display: flex;
  flex-direction: column;
  min-width: 0;
  word-wrap: break-word;
  background-color: #fff;
  background-clip: border-box;
  border: 1px solid rgba(0, 0, 0, 0.125);
  border-radius: 0.25rem;
}

.card > hr {
  margin-right: 0;
  margin-left: 0;
}

.card > .list-group:first-child .list-group-item:first-child {
  border-top-left-radius: 0.25rem;
  border-top-right-radius: 0.25rem;
}

.card > .list-group:last-child .list-group-item:last-child {
  border-bottom-right-radius: 0.25rem;
  border-bottom-left-radius: 0.25rem;
}

.card-body {
  flex: 1 1 auto;
  padding: 1.25rem 1.25rem;
}

.card-title {
  margin-bottom: 0.75rem;
}

.card-subtitle {
  margin-top: -0.375rem;
  margin-bottom: 0;
}

.card-text:last-child {
  margin-bottom: 0;
}

.card-link:hover {
  text-decoration: none;
}

.card-link + .card-link {
  margin-left: 1.25rem;
}

.card-header{
  padding: 0.75rem 1.25rem;
  margin-bottom: 0;
  background-color: rgba(0, 0, 0, 0.03);
  border-bottom: 1px solid rgba(0, 0, 0, 0.125);
  font-size : 25px;
}

.card-header:first-child {
  border-radius: calc(0.25rem - 1px) calc(0.25rem - 1px) 0 0;
}

.card-header + .list-group .list-group-item:first-child {
  border-top: 0;
}

.card-footer {
  padding: 0.75rem 1.25rem;
  background-color: rgba(0, 0, 0, 0.03);
  border-top: 1px solid rgba(0, 0, 0, 0.125);
}

.card-footer:last-child {
  border-radius: 0 0 calc(0.25rem - 1px) calc(0.25rem - 1px);
}

.card-header-tabs {
  margin-right: -0.625rem;
  margin-bottom: -0.75rem;
  margin-left: -0.625rem;
  border-bottom: 0;
}

.card-header-pills {
  margin-right: -0.625rem;
  margin-left: -0.625rem;
}

.card-img-overlay {
  position: absolute;
  top: 0;
  right: 0;
  bottom: 0;
  left: 0;
  padding: 1.25rem;
}

.card-img,
.card-img-top,
.card-img-bottom {
  width: 100%;
}

.card-img,
.card-img-top {
  border-top-left-radius: calc(0.25rem - 1px);
  border-top-right-radius: calc(0.25rem - 1px);
}

.card-img,
.card-img-bottom {
  border-bottom-right-radius: calc(0.25rem - 1px);
  border-bottom-left-radius: calc(0.25rem - 1px);
}

.card-group > .card {
  margin-bottom: 0.75rem;
}

@media (min-width: 576px) {
  .card-group {
    display: flex;
    flex-flow: row wrap;
  }
  .card-group > .card {
    flex: 1 0 0%;
    margin-bottom: 0;
  }
  .card-group > .card + .card {
    margin-left: 0;
    border-left: 0;
  }
  .card-group > .card:not(:last-child) {
    border-top-right-radius: 0;
    border-bottom-right-radius: 0;
  }
  .card-group > .card:not(:last-child) .card-img-top,
  .card-group > .card:not(:last-child) .card-header {
    border-top-right-radius: 0;
  }
  .card-group > .card:not(:last-child) .card-img-bottom,
  .card-group > .card:not(:last-child) .card-footer {
    border-bottom-right-radius: 0;
  }
  .card-group > .card:not(:first-child) {
    border-top-left-radius: 0;
    border-bottom-left-radius: 0;
  }
  .card-group > .card:not(:first-child) .card-img-top,
  .card-group > .card:not(:first-child) .card-header {
    border-top-left-radius: 0;
  }
  .card-group > .card:not(:first-child) .card-img-bottom,
  .card-group > .card:not(:first-child) .card-footer {
    border-bottom-left-radius: 0;
  }
}
</style>
{% endblock %}


<div class = "row">
    <div class = "col-md-12 text-center">
        <h1> Flash Cards </h1>
        <br>
    </div>
</div>

{% for row in rows %}
<div class = "row">
    {% for item in row %}
    <div class="col-md-4">
        <div class="card text-white bg-dark mt-5">
            <div class="card-header text-center"> {{item['word']}} </div>
            <div class="card-body">
                <!-- <h5 class="card-title">card title</h5> -->
                <p class="collapse card-text" id = "{{item['word']}}"> 
                {% for meaning in item['meanings'] %}
                    <span style = "font-weight: bold;"> {{meaning['part']}} </span> <br>
                    {{meaning['def']}}
                    <br><br>
                {% endfor %}
                </p>
                <h5 class="text-center"><a data-toggle="collapse" data-target="#{{item['word']}}"> Show Meaning &raquo;</a></h5>
            </div>
        </div>
    </div>
    {% endfor %}
</div>
<br>
<br>
{% endfor %}

{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block app_content %}

{% block styles %}
    {{ super() }}
    <style>
        @import url(https://fonts.googleapis.com/css?family=Open+Sans:400italic);
        blockquote{
        font-size: 1.4em;
        width:60%;
        margin:50px auto;
        font-family:Open Sans;
        font-style:italic;
        color: #555555;
        padding:1.2em 30px 1.2em 75px;
        border-left:8px solid #78C0A8 ;
        line-height:1.6;
        position: relative;
        background:#EDEDED;
        }

        blockquote::before{
        font-family:Arial;
        content: "\201C";
        color:#78C0A8;
        font-size:4em;
        position: absolute;
        left: 10px;
        top:-10px;
        }

        blockquote::after{
        content: '';
        }

        blockquote span{
        display:block;
        color:#333333;
        font-style: normal;
        font-weight: bold;
        margin-top:1em;
        }

        h1 { color: #111; font-family: 'Helvetica Neue', sans-serif; font-size: 200px; font-weight: bold; letter-spacing: -1px; line-height: 1; text-align: center; }
        h2 { color: #111; font-family: 'Open Sans', sans-serif; font-size: 30px; font-weight: 300; line-height: 32px; margin: 0 0 72px; text-align: center; }
    </style>
{% endblock %}

<div class="row">
    <h1 class = 'text-center'>Diktionary</h1>
            <blockquote>
                    The more words you know, the more clearly and powerfully you will think.. and the more ideas you will invite into your mind.
                <span>Wilfred Funk</span>
            </blockquote>
</div>
{% endblock %}

app/templates/profile.html
{% extends "base.html" %}

{% block app_content %}
<div class = "row">
    <div class = 'col-md-8'>
        <h2> {{'Welcome, ' + name + "!"}} </h2>
        <br>
        <h4> {{'You have ' + num + ' words in your favorites'}}</h4>
        <h4> Review them anytime in the Flash Cards section!</h4>
    </div>
    <div class = 'text-right col-md-4'>
            <h4>{{'Username: ' + user.username}}</h4>
            <h4>{{'Email: ' + user.email}}</h4>
    </div>
</div>
{% endblock %}

app/templates/search.html
{% extends "base.html" %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block app_content %}

<div class="row">
    <div class="col-md-4">
        <h1> Search </h1>
        {{ wtf.quick_form(form) }}
    </div>
    {% if not dne and word != "" %}
        <br>
        <br>
        <div class="col-md-4 col-md-offset-2">
            {% if is_favorite %}
                <a href = "{{url_for('main.remove_from_favorites', word=word)}}" ><button type="button" class="btn btn-danger btn-md"> Remove from Favorites </button></a>
            {% else %}
                <a href = "{{ url_for('main.add_to_favorites', word=word)}}" ><button type="button" class="btn btn-success btn-md"> Add to Favorites </button></a>
            {% endif %}
        </div>
    {% endif %}
</div>

{% if dne %}
<br>
<h2> Word Does Not Exist in dictionary. </h2>
<br>
{% elif data is not none %}
<br>
<h2> {{ data|length }} Meanings found </h2>
<br>

{% for item in data %}
<div class = "row">
    <div class="col-md-4">
        <div class="list-group">
            <a href="" class="list-group-item list-group-item-success">
                <h3 class="list-group-item-heading"> {{item['fl']}} </h3>
                <p class="list-group-item-text"> {{item['shortdef'][0]}} </p>
            </a>
        </div>
    </div>
</div>
{% endfor %}
{% endif %}

{% endblock %}